
# name of topic to subscribe and publish
topic:
  scan: /scan
  odom: /odom
  nav: /drive


# configuration values for driving algorithm
driving:
  robot_scale: 0.15
  threshold: 2.0
  filter_size: 5.0
  filter_scale: 1.8
