
# name of topic to subscribe and publish
topic:
  scan: /scan
  odom: /odom
  nav: /drive


# configuration values for driving algorithm
driving:
  robot_scale: 0.5
  threshold: 2
  filter_size: 5
  filter_scale: 2
