# reference points
reference_point:
  filepath: /wps/berlin_4.csv
  distance: 1.3

# name of topic to subscribe and publish
topic:
  scan: /scan
  odom: /odom
  nav: /drive


# configuration values for driving algorithm
driving:
  speed_max: 6.5
  speed_min: 2.5
  robot_scale: 0.3
  threshold: 6.0
  gap_size: 2
  filter_scale: 1.1
  gap_theta_gain: 40.0
  ref_theta_gain: 1.0
